name: flutter_compass
description: A Flutter compass. The heading varies from 0-360, 0 being north.
version: 1.0.0
homepage: https://github.com/hemanthrajv/flutter_compass

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.hemanthraj.fluttercompass
        pluginClass: FlutterCompassPlugin
      ios:
        pluginClass: FlutterCompassPlugin
